<?php

namespace Database\Factories;

use Illuminate\Database\Eloquent\Factories\Factory;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\User>
 */
class SeniorsFactory extends Factory
{
    /**
     * The current password being used by the factory.
     */
    protected static ?string $password;

    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        $age = $this->faker->numberBetween(60, 100);

        $birthdate = now()->subYears($age)->toDateString();

        $filipinoStreet = [
            'Maligaya Street',
            'Mabait Drive',
            'Malolos Avenue',
            'Daisy Road',
            'Camia Boulevard',
            'Sampaguita Street',
            'Rosal Drive',
            'Ruby Avenue',
            'Emerald Boulevard',
            'Gemini Street',
            'Sunflower Drive',
            'Tulip Road',
            'Jade Avenue',
            'Pearl Boulevard',
            'Santos Street',
            'Magnolia Avenue',
            'Ilang-Ilang Drive',
            'Waling-Waling Boulevard',
            'Champaca Street',
            'Dama de Noche Avenue',
            'Venus Road',
            'Saturn Street',
            'Mars Drive',
            'Orion Boulevard',
            'Aurora Avenue',
            'Luna Street',
            'Kalayaan Drive',
            'Masaya Road',
            'Pag-asa Street',
            'Matahimik Avenue',
            'Makisig Boulevard',
            'Marangal Drive',
            'Magiting Street',
            'Mabuhay Road',
            'Mapayapa Avenue',
            'Matatag Drive',
            'Matapat Boulevard',
            'Matamis Street',
            'Mahinhin Drive',
            'Maharlika Avenue',
            'Anahaw Road',
            'Acacia Street',
            'Yakal Boulevard',
            'Narra Drive',
            'Kamagong Street',
            'Molave Avenue',
            'Banaba Road',
            'Talisay Drive',
            'Santol Street',
            'Mangga Avenue',
            'Bayabas Drive',
            'Makopa Street',
            'Kalamansi Road',
            'Atis Drive',
            'Langka Street',
            'Papaya Boulevard',
            'Guyabano Avenue',
            'Siniguelas Drive',
            'Avocado Street',
            'Chico Road',
            'Guava Drive',
            'Balete Boulevard',
            'Pineapple Avenue',
            'Cherry Drive',
            'Rambutan Street',
            'Dalandan Road',
            'Jasmine Street',
            'Azucena Drive',
            'Gardenia Boulevard',
            'Lily Avenue',
            'Poinsettia Street',
            'Gumamela Drive',
            'Hydrangea Road',
            'Bluebell Boulevard',
            'Iris Avenue',
            'Violeta Street',
            'Zinnia Drive',
            'Carnation Road',
            'Hibiscus Boulevard',
            'Marigold Street',
            'Cosmos Drive',
            'Petunia Road',
            'Lavender Avenue',
            'Rose Street',
            'Gladiola Boulevard',
            'Peridot Avenue',
            'Topaz Street',
            'Amethyst Drive',
            'Opal Road',
            'Diamond Boulevard',
            'Sapphire Street',
            'Garnet Drive',
            'Turquoise Road',
            'Citrine Avenue',
            'Amber Street',
            'Coral Boulevard',
            'Onyx Drive',
            'Aquamarine Avenue',
            'Silver Street',
            'Gold Boulevard',
            'Coral Drive',
            'Emerald Road',
            'Ivory Street',
            'Quartz Avenue',
            'Marble Boulevard',
            'Jade Street',
            'Diamond Drive',
            'Bamboo Road',
            'Coconut Avenue',
            'Mango Street',
            'Banana Boulevard',
            'Pandan Drive',
            'Lime Road',
            'Plumeria Avenue',
            'Mangosteen Street',
            'Jackfruit Boulevard',
            'Lychee Drive',
            'Ginger Road',
            'Papaya Street',
            'Ficus Boulevard',
            'Aloe Avenue',
            'Soursop Drive',
            'Cypress Street',
            'Acacia Road',
            'Cedar Drive',
            'Kahoy Avenue',
            'Laurel Street',
            'Myrtle Boulevard',
            'Willow Road',
            'Ash Tree Drive',
            'Elm Street',
            'Oak Boulevard',
            'Redwood Avenue',
            'Maple Road',
            'Pine Street',
            'Hickory Drive',
            'Spruce Boulevard',
            'Birch Avenue',
            'Cypress Drive',
            'Douglas Fir Road',
            'Walnut Street',
            'Magnolia Boulevard',
            'Sago Palm Drive',
            'Pomegranate Avenue',
            'Cacao Street',
            'Tamarind Boulevard',
            'Durian Road',
            'Langka Avenue',
            'Bamboo Street',
            'Sandalwood Drive',
            'Camphor Road',
            'Mahogany Boulevard',
            'Chestnut Avenue',
            'Fir Street',
            'Aspen Boulevard',
            'Juniper Drive',
            'Cypress Road',
            'Ginkgo Avenue',
            'Hibiscus Street',
            'Calamansi Boulevard',
            'Balsa Avenue',
            'Guava Road',
            'Betel Nut Street',
            'Bittermelon Boulevard',
            'Fennel Avenue',
            'Chamomile Drive',
            'Oregano Road',
            'Sage Street',
            'Rosemary Boulevard',
            'Thyme Avenue',
            'Basil Street',
            'Mint Drive',
            'Cilantro Road',
            'Parsley Avenue',
            'Dandelion Boulevard',
            'Bay Laurel Drive',
            'Lavender Road',
            'Eucalyptus Avenue',
            'Rue Street',
            'Marjoram Boulevard',
            'Coriander Drive',
            'Oregano Street',
            'Fennel Boulevard',
            'Aloe Road',
            'Basil Boulevard',
            'Chili Pepper Avenue',
            'Clove Street',
            'Bayberry Road',
            'Ginger Boulevard',
            'Turmeric Drive',
            'Chrysanthemum Avenue',
            'Balsam Street',
            'Thyme Road',
            'Mint Boulevard',
            'Stevia Drive',
            'Cilantro Boulevard',
            'Parsley Avenue',
            'Balsam Drive',
            'Cedar Street',
            'Ivy Avenue',
            'Cypress Boulevard',
            'Laurel Drive',
            'Eucalyptus Street',
            'Magnolia Road',
            'Azalea Boulevard',
            'Buttercup Avenue',
            'Lilac Drive',
            'Aster Street',
            'Begonia Boulevard',
            'Daffodil Avenue',
            'Mimosa Drive',
            'Sunflower Road',
            'Hydrangea Boulevard',
            'Plumeria Street',
            'Jasmine Road',
            'Cineraria Drive',
            'Zinnia Boulevard',
            'Saffron Street',
            'Bamboo Avenue',
            'Lotus Boulevard',
            'Poppy Drive',
            'Geranium Avenue',
            'Amaryllis Street',
            'Snapdragon Boulevard',
            'Freesia Drive',
            'Dandelion Street',
            'Gumamela Avenue',
            'Petunia Boulevard',
            'Calla Lily Road',
            'Lobelia Street',
            'Wisteria Drive',
            'Alstroemeria Avenue',
            'Fuchsia Boulevard',
            'Gardenia Drive',
            'Tuberose Street',
            'Gloxinia Road',
            'Impatiens Boulevard',
            'Ageratum Avenue',
            'Lantana Street',
            'Bluebell Road',
            'Hellebore Drive',
            'Salvia Boulevard',
            'Kalanchoe Avenue',
            'Pansy Drive',
            'Rhododendron Boulevard',
            'Gerbera Avenue',
            'Bells of Ireland Street',
            'Bergamot Boulevard',
            'Chrysanthemum Drive',
            'Dahlia Street',
            'Lantana Road',
            'Thyme Boulevard',
            'Lemon Balm Avenue',
            'Bougainvillea Drive',
            'Gladiolus Street',
            'Lotus Road',
            'Cattleya Boulevard',
            'Butterfly Bush Avenue',
            'Stock Drive',
            'Crocus Street',
            'Aster Boulevard',
            'Cineraria Road'
        ];

        $philippineCities = [
            'Caloocan City',
            'Quezon City',
            'Manila',
            'Cebu City',
            'Davao City',
            'Zamboanga City',
            'Baguio City',
            'Iloilo City',
            'Taguig City',
            'Cavite City',
            'General Santos City',
            'Makati City',
            'Pasig City',
            'Marikina City',
            'San Juan City',
            'Las Piñas City',
            'Parañaque City',
            'Malabon City',
            'Navotas City',
            'Mandaluyong City',
            'Calamba City',
            'Bacoor City',
            'Cagayan de Oro City',
            'Lapu-Lapu City',
            'Angeles City',
            'San Fernando City (Pampanga)',
            'Tarlac City',
            'San Carlos City (Pangasinan)',
            'Iligan City',
            'Digos City',
            'Tacloban City',
            'Tagum City',
            'Puerto Princesa City',
            'Ormoc City',
            'Bayugan City',
            'Dipolog City',
            'Marawi City',
            'Cotabato City',
            'Legazpi City',
            'Naga City',
            'Cabanatuan City',
            'Santiago City',
            'Tuguegarao City',
            'San Jose City (Occidental Mindoro)',
            'San Jose del Monte City',
            'Mandaue City',
            'Dumaguete City',
            'Calapan City',
            'Zamboanga del Norte',
            'Surigao City',
            'Butuan City',
            'Tagbilaran City',
            'Talisay City',
            'Taguig City',
            'General Trias City',
            'Bacolod City',
            'Antipolo City',
            'Muntinlupa City',
            'Bocaue City',
            'Batangas City',
            'San Pablo City',
            'San Mateo City',
            'Taytay City',
            'Malolos City',
            'Sta. Rosa City',
            'Caloocan City',
            'Lipa City',
            'Tarlac City',
            'Olongapo City',
            'San Juan City',
            'Dumaguete City',
            'Iloilo City',
            'Bacolod City',
            'Marikina City',
            'Biñan City',
            'Batangas City',
            'Lucena City',
            'Sorsogon City',
            'Valenzuela City',
            'Muntinlupa City',
            'Mandaluyong City',
            'Magsaysay City',
            'Pateros City',
            'Quezon City',
            'Puerto Princesa City',
            'Santiago City',
            'Davao City',
            'Baguio City',
            'Digos City',
            'Cotabato City',
            'Cagayan de Oro City',
            'General Santos City',
            'Cebu City',
            'Cebu City',
            'Laoag City',
            'Marikina City',
            'Masbate City',
            'Pasay City',
            'San Fernando City',
            'Tacloban City',
            'Pangasinan City',
            'Zamboanga City',
            'Manila City',
            'Dagupan City',
            'Butuan City',
            'Cagayan de Oro City',
            'Zamboanga City',
            'Zamboanga del Sur',
            'Quezon City',
            'Olongapo City',
            'Angeles City',
            'Iligan City',
            'Santiago City',
            'Tagum City',
            'Manila',
            'Quezon City',
            'Iloilo City',
            'Marawi City',
            'Mandaue City',
            'Makati City',
            'Tagbilaran City',
            'Navotas City',
            'Muntinlupa City',
            'Cebu City',
            'Taguig City',
            'Marikina City',
            'San Juan City',
            'Parañaque City',
            'Bacoor City',
            'Marikina City',
            'San Jose City',
            'Lucena City',
            'La Carlota City',
            'Valenzuela City',
            'Iligan City',
            'Marikina City',
            'Sorsogon City',
            'Malabon City',
            'Parañaque City',
            'Laoag City',
            'Olongapo City',
            'Bacolod City',
            'Roxas City',
            'Puerto Princesa City',
            'Dipolog City',
            'Baguio City',
            'Iloilo City',
            'Tagbilaran City',
            'Santiago City',
            'San Fernando City',
            'Davao City',
            'Cebu City',
            'Mandaluyong City',
            'Tarlac City',
            'Tagum City',
            'Caloocan City',
            'Pasig City',
            'Cebu City',
            'Taguig City',
            'Batangas City',
            'San Pedro City',
            'Talisay City',
            'San Juan City',
            'Tacloban City',
            'Cebu City',
            'Antipolo City',
            'Dumaguete City',
            'Legazpi City',
            'Lucena City',
            'Bayawan City',
            'Tuguegarao City',
            'Zamboanga City',
            'Manila City',
            'Pasay City',
            'San Juan City',
            'Zamboanga City',
            'Tacloban City',
            'Tuguegarao City',
            'Davao City',
            'Malolos City',
            'Lucena City',
            'Naga City',
            'Iligan City',
            'Cebu City',
            'Roxas City',
            'Cagayan de Oro City',
            'Tarlac City',
            'Davao City',
            'Bacolod City',
            'Iloilo City',
            'Quezon City',
            'Taguig City',
            'Cebu City',
            'Antipolo City',
            'Muntinlupa City',
            'Dumaguete City',
            'Baguio City',
            'Zamboanga City',
            'Bacolod City',
            'San Pedro City',
            'Tacloban City',
            'Tagbilaran City',
            'Valenzuela City',
            'Pasig City',
            'Cebu City',
            'Lipa City',
            'Tarlac City',
            'San Fernando City',
            'San Juan City',
            'Quezon City',
            'Cebu City',
            'Marikina City',
            'Santiago City',
            'Davao City',
            'Iloilo City',
            'Zamboanga City',
            'Digos City',
            'Tagbilaran City',
            'Olongapo City',
            'Caloocan City',
            'Talisay City',
            'Makati City',
            'General Santos City',
            'Marawi City',
            'San Carlos City (Pangasinan)',
            'Taguig City',
            'Mandaluyong City',
            'Tagum City',
            'Davao City',
            'Makati City',
            'Cebu City',
            'Iloilo City',
            'Zamboanga City',
            'Baguio City',
            'Iligan City'
        ];

        $barangays = [
            'Barangay 165',
            'Barangay 166',
            'Barangay 167',
            'Barangay 168',
            'Barangay 169',
            'Barangay 170',
            'Barangay 171',
            'Barangay 172',
            'Barangay 173',
            'Barangay 174',
            'Barangay 175',
            'Barangay 176-A',
            'Barangay 176-B',
            'Barangay 176-C',
            'Barangay 176-D',
            'Barangay 176-E',
            'Barangay 176-F',
            'Barangay 177',
            'Barangay 178',
            'Barangay 179',
            'Barangay 180',
            'Barangay 181',
            'Barangay 182',
            'Barangay 183',
            'Barangay 184',
            'Barangay 185',
            'Barangay 186',
            'Barangay 187',
            'Barangay 188'
        ];

        $houseNumber = $this->faker->numberBetween(1000, 9999);
        $phase = 'Phase ' . $this->faker->numberBetween(1, 10);
        $block = 'Block ' . $this->faker->numberBetween(1, 90);
        $lot = 'Lot ' . $this->faker->numberBetween(1, 90);
        $barangayNo = $this->faker->randomElement($barangays);
        $barangayIndex = array_search($barangayNo, $barangays) + 1;
        $filipinoStreet = $this->faker->randomElement($filipinoStreet);
        $address = "{$houseNumber} {$phase} {$block} {$lot} {$filipinoStreet}, {$barangayNo}, Caloocan City";

        $maleNames = [
            'John',
            'Mark',
            'Michael',
            'James',
            'Robert',
            'William',
            'David',
            'Richard',
            'Joseph',
            'Charles',
            'Thomas',
            'Daniel',
            'Matthew',
            'Anthony',
            'Donald',
            'Paul',
            'Andrew',
            'Joshua',
            'Samuel',
            'Kevin',
            'Brian',
            'George',
            'Edward',
            'Ronald',
            'Jack',
            'Jason',
            'Justin',
            'Larry',
            'Scott',
            'Eric',
            'Stephen',
            'Timothy',
            'Daniel',
            'Adam',
            'Nathan',
            'Jose',
            'Luis',
            'Carlos',
            'Eduardo',
            'Antonio',
            'Francisco',
            'Julio',
            'Fernando',
            'Roberto',
            'Javier',
            'Victor',
            'Jorge',
            'Rafael',
            'Ricardo',
            'Gabriel',
            'Alberto',
            'Manuel',
            'Pedro',
            'Juan',
            'Ramon',
            'Marco',
            'Enrique',
            'Diego',
            'Miguel',
            'Fernando',
            'Cesar',
            'Felipe',
            'Hector',
            'Oscar',
            'Arturo',
            'Salvador',
            'Victor',
            'Jesus',
            'Ramiro',
            'Gilberto',
            'Santiago',
            'Oscar',
            'Raul',
            'Ariel',
            'Bernardo',
            'Benjamin',
            'Luis Miguel',
            'Maximo',
            'Ricardo',
            'Hernando',
            'Carlos Alberto',
            'Rolando',
            'Nelson',
            'Benedicto',
            'Alfredo',
            'Felix',
            'Manuelito',
            'Nicolas',
            'Marcos',
            'Gil',
            'Lorenzo',
            'Andres',
            'Carlos Manuel',
            'Alfonso',
            'Ezequiel',
            'Salvador',
            'Rogelio',
            'Armando',
            'Hugo',
            'Ismael',
            'Carlos Eduardo',
            'Angelo',
            'Benito',
            'Nestor',
            'Martin',
            'Esteban',
            'Javier Luis',
            'Juan Carlos',
            'Wilfredo',
            'Felipe Juan',
            'Julian',
            'Pablo',
            'Ricardo Luis',
            'Patricio',
            'Ignacio',
            'Rudy',
            'Orlando',
            'Daniel Luis',
            'Joaquín',
            'Claudio',
            'Victor Hugo',
            'Hernan',
            'Francisco Javier',
            'Robinson',
            'Maximiliano',
            'Emilio',
            'Humberto',
            'Vicente',
            'Lazaro',
            'Victor Manuel',
            'Santiago Luis',
            'Joaquin Manuel',
            'Arnaldo',
            'Aurelio',
            'Eladio',
            'Teodoro',
            'Ubaldo',
            'Enzo',
            'Emilio',
            'Dario',
            'Renato',
            'Fausto',
            'Elias',
            'Rodrigo',
            'Felix Antonio',
            'Antonio Luis',
            'Horacio',
            'Raul Manuel',
            'Saul',
            'Antonio Miguel',
            'Samuel Luis',
            'Victoriano',
            'David Luis',
            'Dante',
            'Gustavo',
            'Raul Eduardo',
            'Martín',
            'Luis Fernando',
            'Benjamín',
            'Cristian',
            'Raul José',
            'Leonardo',
            'Isidro',
            'Agustin',
            'Emiliano',
            'Omar',
            'Adrián',
            'Evan',
            'Ricardo Javier',
            'Luis Antonio',
            'Ibrahim',
            'Oscar Eduardo',
            'Carmelo',
            'Tomas',
            'Enrique Luis',
            'Jorge Luis',
            'Adolfo',
            'Ramón',
            'Marcelo',
            'Hector Luis',
            'Andres Luis',
            'Joaquin Felipe',
            'David Antonio',
            'Félix',
            'Giovanni',
            'Agustin Luis',
            'Héctor Eduardo',
            'Cristian Luis',
            'Ruben',
            'Arturo Luis',
            'Rodrigo Luis',
            'Alfredo Luis',
            'Santiago Manuel',
            'Abel',
            'Juan Manuel',
            'Carlos Javier',
            'Raúl Luis',
            'Felipe Manuel',
            'Julian Luis',
            'Anibal',
            'Victor Luis',
            'Emilio Luis',
            'José Manuel',
            'Pablo Luis',
            'Tadeo',
            'Luis Ángel',
            'Brayan',
            'Carlos Jesús',
            'Raúl Antonio',
            'Victoriano Luis',
            'Eugenio',
            'Ricardo Antonio',
            'Jose Luis',
            'Luciano',
            'Adrian Luis',
            'Agustín Antonio',
            'Braulio',
            'Luis Enrique',
            'Rodolfo',
            'Luis Alberto',
            'Julian Antonio',
            'Diego Luis',
            'Luis David',
            'Carlos Enrique',
            'José Antonio',
            'Emiliano Luis',
            'Ismael Luis',
            'Alfredo Enrique',
            'Antonio Enrique',
            'Marcelo Luis',
            'José Enrique',
            'Carlos Arturo',
            'Gerardo',
            'Miguel Ángel',
            'Eliseo',
            'Carlos Agustín',
            'Felipe Luis',
            'Carlos Ricardo',
            'Omar Luis',
            'Antonio Arturo',
            'Pedro Luis',
            'Félix Luis',
            'Héctor Luis',
            'Carlos José',
            'David Alberto',
            'Arturo Enrique',
            'José Ricardo',
            'Maximiliano Luis',
            'Alejandro',
            'Víctor Luis',
            'Carlos Benito',
            'Luis Gustavo',
            'Antonio Luis',
            'Carlos Felipe',
            'José Pablo',
            'Leonardo Luis',
            'José Andrés',
            'Pedro José',
            'Ezequiel Luis',
            'José Antonio Luis',
            'Agustín Luis',
            'Lázaro Luis',
            'Pedro Rafael',
            'Juan Felipe',
            'Guillermo',
            'Luis Juan',
            'José Francisco',
            'Alejo',
            'Marco Antonio',
            'Fabián',
            'Antonio José',
            'Juan Felipe',
            'Raúl Felipe',
            'Ricardo Alberto',
            'José Luis',
            'Leopoldo',
            'Rodrigo Manuel',
            'Salvador Luis',
            'Benicio',
            'Luis Eduardo',
            'Víctor Manuel',
            'José Salvador',
            'Gonzalo',
            'David Rafael',
            'Leandro',
            'Hugo Luis',
            'Juan Enrique',
            'Beto',
            'Bautista',
            'Benito Luis',
            'Álvaro',
            'Rogelio Luis',
            'Santiago Enrique',
            'Alberto Luis',
            'Cristian Enrique',
            'Ramiro Luis',
            'Omar Enrique',
            'Benjamín Luis',
            'Luis Felipe',
            'Felipe José',
            'Carlos Gonzalo',
            'Cristian José',
            'Esteban',
            'Miguel Luis',
            'Carlos Iván',
            'Luis Antonio Enrique',
            'Jorge Alberto',
            'Efraín',
            'Ramón Luis',
            'Alejo Luis',
            'Héctor Antonio',
            'Luis Adrián',
            'Santos',
            'Guido',
            'José Alejandro',
            'Carlos Martín',
            'Nicolás',
            'José Eugenio',
            'Aurelio',
            'Patricio',
            'Carlos Raúl',
            'José Ángel',
            'Francisco Luis',
            'Raúl Francisco',
            'Felipe José Luis',
            'Juan Antonio',
            'Julián José',
            'Sebastián',
            'César Luis',
            'José Luis Eduardo',
            'Luis Antonio Enrique'
        ];

        $femaleNames = [
            'Mary',
            'Jennifer',
            'Linda',
            'Patricia',
            'Elizabeth',
            'Barbara',
            'Susan',
            'Jessica',
            'Sarah',
            'Margaret',
            'Dorothy',
            'Laura',
            'Helen',
            'Nancy',
            'Karen',
            'Betty',
            'Ruth',
            'Sharon',
            'Kimberly',
            'Deborah',
            'Cynthia',
            'Amy',
            'Angela',
            'Virginia',
            'Diane',
            'Julie',
            'Madison',
            'Sophia',
            'Isabella',
            'Charlotte',
            'Ava',
            'Mia',
            'Emma',
            'Harper',
            'Ella',
            'Maria',
            'Angelica',
            'Camille',
            'Rosa',
            'Luz',
            'Carmela',
            'Teresa',
            'Grace',
            'Monica',
            'Leah',
            'Samantha',
            'Nina',
            'Liza',
            'Joanna',
            'Patricia',
            'Bea',
            'Maricel',
            'Chloe',
            'Kristina',
            'Jacqueline',
            'Celeste',
            'Rachelle',
            'Marie',
            'Alicia',
            'Vanessa',
            'Zoe',
            'Margarita',
            'Evelyn',
            'Gina',
            'Charity',
            'Marisol',
            'Isabel',
            'Francisca',
            'Eleanor',
            'Helen',
            'Norma',
            'Olivia',
            'Veronica',
            'Kristen',
            'Theresa',
            'Raquel',
            'Ivy',
            'Beatriz',
            'Diana',
            'Marilyn',
            'Nina',
            'Felicity',
            'Michele',
            'Florence',
            'Frances',
            'Danica',
            'Ruth',
            'Dahlia',
            'Sofia',
            'Jasmine',
            'Rosalie',
            'Carla',
            'Lucia',
            'Regina',
            'Tess',
            'Elsa',
            'Alicia',
            'Sylvia',
            'Rita',
            'Janet',
            'Faye',
            'Darlene',
            'Anabelle',
            'Tina',
            'Lynne',
            'Mae',
            'Rhea',
            'Yvette',
            'Adela',
            'Pamela',
            'Raquel',
            'Janice',
            'Evelyn',
            'Valerie',
            'Marla',
            'Imelda',
            'Sheryl',
            'Yasmin',
            'Lorna',
            'Frieda',
            'Maeve',
            'Joan',
            'Vivian',
            'Selena',
            'Kaitlyn',
            'Amanda',
            'Louise',
            'Paulette',
            'Judy',
            'Kayla',
            'Amanda',
            'Emily',
            'Rebecca',
            'Miranda',
            'Barbara',
            'Harriet',
            'Audrey',
            'Lindsey',
            'Esther',
            'Danielle',
            'Delia',
            'Veronica',
            'Elena',
            'Cecilia',
            'Kay',
            'Marian',
            'Gwendolyn',
            'Jocelyn',
            'Adriana',
            'Helena',
            'Katherine',
            'Kirsten',
            'Deanna',
            'Wendy',
            'Delilah',
            'Tiffany',
            'Sandy',
            'Rosalind',
            'Eunice',
            'Irene',
            'Rochelle',
            'Diana',
            'Clarissa',
            'Mia',
            'Leona',
            'Martha',
            'Bridget',
            'Angelina',
            'Teresa',
            'Connie',
            'Patty',
            'Sheryl',
            'Opal',
            'Loretta',
            'Marissa',
            'Judith',
            'Gloria',
            'Joanne',
            'Gilda',
            'Maggie',
            'Rosanne',
            'Krista',
            'Mina',
            'Rocío',
            'Regine',
            'Wilma',
            'Dianne',
            'Shirley',
            'Sally',
            'Melanie',
            'Lydia',
            'Kathy',
            'Anita',
            'Erika',
            'Eileen',
            'Tanya',
            'Bianca',
            'Darlene',
            'Karen',
            'Iris',
            'Alma',
            'Maxine',
            'Hope',
            'Rita',
            'Carmen',
            'Michele',
            'Carolina',
            'Isabelle',
            'Renee',
            'Louise',
            'Joyce',
            'Angeline',
            'Amor',
            'Catalina',
            'Nadine',
            'Nicole',
            'Claudia',
            'Mae',
            'Florencia',
            'Alyssa',
            'Ariana',
            'Angel',
            'Marietta',
            'Marian',
            'Annabelle',
            'Anastacia',
            'Geneva',
            'Blanca',
            'Juliana',
            'Carla',
            'Wendy',
            'Rosella',
            'Rosalinda',
            'Terry',
            'Celina',
            'Amparo',
            'Glenda',
            'Daisy',
            'Isabelita',
            'Margarita',
            'Rosie',
            'Sienna',
            'Angela',
            'Cheryl',
            'Selena',
            'Cynthia',
            'Tina',
            'Gretchen',
            'Olivia',
            'Shannon',
            'Lydia',
            'Renee',
            'Mona',
            'Jessie',
            'Betty',
            'Nancy',
            'Sasha',
            'Gabriella',
            'Sarah',
            'Catherine',
            'Pauline',
            'Clarabelle',
            'Lorena',
            'Brenda',
            'Desiree',
            'Corazon',
            'Jacinta',
            'Esperanza',
            'Natividad',
            'Belen',
            'Marivic',
            'Cecilia',
            'Dina',
            'Violeta',
            'Imelda',
            'Danica',
            'Lorelei',
            'Dulce',
            'Raiza',
            'Wilhelmina',
            'Fay',
            'Beverly',
            'Celia',
            'Minda',
            'Myra',
            'Loretta',
            'Adelaida',
            'Sylvia',
            'Monique',
            'Rita',
            'Zara',
            'Liza',
            'Juliana',
            'Aimee',
            'Mary Jane',
            'Herminia',
            'Angelita',
            'Lourdes',
            'Araceli',
            'Rosemary',
            'Francesca',
            'Tina',
            'Evangeline',
            'Danica',
            'Benedicta',
            'Leonora',
            'Anabella',
            'Adela',
            'Venus',
            'Estrella',
            'Melanie',
            'Sandy',
            'Danielle',
            'Erma',
            'Lara',
            'Cassandra',
            'Elisabeth',
            'Clara',
            'Valerie',
            'Roxanne',
            'Carmela',
            'Susana',
            'Thelma',
            'Hilda',
            'Noreen',
            'Doreen',
            'Victoria',
            'Lynette',
            'Kristina',
            'Patricia',
            'Edith',
            'Gloria',
            'Elsie',
            'Edna',
            'Lilian',
            'Esther',
            'Geraldine',
            'Imelda',
            'Lilian',
            'Darlene'
        ];

        $filipinoLastNames = [
            'Cabigon',
            'Santiago',
            'Palomares',
            'Tonio',
            'Aquino',
            'Bautista',
            'Cruz',
            'Dela Cruz',
            'Gonzales',
            'Garcia',
            'López',
            'Martinez',
            'Reyes',
            'Santos',
            'Torres',
            'Delos Reyes',
            'Bañez',
            'Flores',
            'Nieves',
            'Salvador',
            'Dizon',
            'Bacani',
            'Velasquez',
            'Cabrera',
            'Pascual',
            'Villanueva',
            'Alvarez',
            'Chua',
            'Sarmiento',
            'Morales',
            'Pineda',
            'Ocampo',
            'Alcantara',
            'Cortez',
            'Alvarado',
            'Mendoza',
            'Labrador',
            'Salinas',
            'Castañeda',
            'De Leon',
            'Vera',
            'Magsaysay',
            'Dela Torre',
            'Ponce',
            'Suarez',
            'Valenzuela',
            'Aguilar',
            'Ramos',
            'Cruzado',
            'Esteban',
            'Sison',
            'Tiongson',
            'San Antonio',
            'Dela Cruz',
            'Del Mundo',
            'De Guzman',
            'De Jesus',
            'De Leon',
            'Delos Santos',
            'De Vera',
            'San Miguel',
            'San Juan',
            'San Pedro',
            'De Ocampo',
            'Del Rosario',
            'De la Torre',
            'De la Cruz',
            'San Vicente',
            'Del Castillo',
            'De la Vega',
            'Bautista',
            'Cruz',
            'Mendoza',
            'Martinez',
            'Riviera',
            'Salas',
            'Rocamora',
            'Santos',
            'Tabujara',
            'Verano',
            'Villanueva',
            'Castillo',
            'Martelino',
            'Misa',
            'Naguit',
            'Alcaraz',
            'Alfonso',
            'Arroyo',
            'Atienza',
            'Bañez',
            'Cabarroguis',
            'Esguerra',
            'Manalo',
            'Matias',
            'Ramos',
            'Villafuerte',
            'Yap',
            'Zaragoza',
            'De Guzman',
            'De la Rosa',
            'Delos Reyes',
            'De Guzman',
            'De Villa',
            'Gumabay',
            'Lacuna',
            'Macapagal',
            'Manalaysay',
            'Natividad',
            'Rosales',
            'Soriano',
            'Villacorta',
            'Barros',
            'Villar',
            'Arias',
            'Aranas',
            'Bermudez',
            'Reyes',
            'Salvador',
            'Tolentino',
            'Calderon',
            'Casimiro',
            'Castro',
            'Guevara',
            'Pineda',
            'Abad',
            'Geronimo',
            'Lopez',
            'Rivera',
            'Alvarado',
            'Diaz',
            'Navarro',
            'Ramos',
            'Arocena',
            'Balaoro',
            'Ebarle',
            'Flores',
            'Laraya',
            'Alba',
            'Delgado',
            'Molina',
            'Santos',
            'Aguilera',
            'Sula',
            'Mira',
            'Balagtas',
            'Legaspi',
            'Mabilog',
            'Gutierrez',
            'Comia',
            'Dumlao',
            'Varela',
            'Baños',
            'Garcia',
            'Dula',
            'Flores',
            'Bagabaldo',
            'Navarro',
            'Catalan',
            'Pioquinto',
            'Suarez',
            'Bote',
            'Concepcion',
            'Estacio',
            'Bautista',
            'Pena',
            'Enriquez',
            'Tajonera',
            'Escobar',
            'Villarreal',
            'Rosales',
            'Llorente',
            'Parreno',
            'Alcazar',
            'Javier',
            'Aguinaldo',
            'Coronel',
            'Calumpang',
            'Sanchez',
            'Lucero',
            'Pallanca',
            'Ferrer',
            'Mendoza',
            'Bermudez',
            'Soliman',
            'Reyes',
            'Ilagan',
            'Mayo',
            'Quintana',
            'Manlapig',
            'San Juan',
            'Amores',
            'Perez',
            'Sebastian',
            'Macadangdang',
            'Simbulan',
            'Urbano',
            'Rivas',
            'Casco',
            'Basilio',
            'De la Cruz',
            'Calderon',
            'Laluna',
            'Pascual',
            'Aranas',
            'Fontanilla',
            'Lacson',
            'Navas',
            'Bajao',
            'Vito',
            'Arroyo',
            'Blanco',
            'Carreon',
            'Diaz',
            'Torres',
            'Zarate',
            'Rocamora',
            'Ravelo',
            'Padilla',
            'Cañas',
            'Lozada',
            'Malamug',
            'Bravo',
            'Echavez',
            'Lim',
            'Fajardo',
            'Mercado',
            'Del Rosario',
            'Sambajon',
            'Singh',
            'Jacinto',
            'Bromer',
            'Bauang',
            'Sabando',
            'Pimentel',
            'Macapagal',
            'Iglesias',
            'Serrano',
            'Carreon',
            'Paniagua',
            'Santos',
            'Solis',
            'Cuenca',
            'Castillo',
            'Liao',
            'Lozada',
            'Caballes',
            'Gatdula',
            'Bariuan',
            'Mompong',
            'Dantoc',
            'Javier',
            'Mendoz',
            'Arias',
            'Calang',
            'Lachica',
            'Pangilinan',
            'Solomon',
            'San Martin',
            'Barit',
            'Aguilar',
            'Delgado',
            'Macalino',
            'Manlapig',
            'Lagrada',
            'Matibag',
            'Sagun',
            'De La Cruz',
            'Mendoza',
            'De Vera',
            'Almasco',
            'Balmes',
            'Visminda',
            'Nunez',
            'Rosaroso',
            'Bohol',
            'Galve',
            'Hernandez',
            'Mercado',
            'Lim',
            'Velez',
            'Teng',
            'Pamaos',
            'Lao',
            'Casiño',
            'Santos',
            'Silva',
            'Benedicto',
            'Sarmiento',
            'Bautista',
            'Calderon',
            'Macalino',
            'Aragon',
            'De La Cruz',
            'Ocampo',
            'Llorente',
            'Acil',
            'Mendoza',
            'Verzosa',
            'Quiñones',
            'Dizon',
            'Robles',
            'Ortiz',
            'Lacson',
            'Tagupa',
            'Bodegas',
            'Baños',
            'Labad',
            'Sese',
            'Enriquez',
            'Villarica',
            'Macadangdang',
            'Bautista',
            'Macapagal',
            'Panganiban',
            'Villar',
            'Macalino',
            'Martinez',
            'Acal',
            'Barrozo',
            'Asturias',
            'Santos',
            'Carlos',
            'Desiderio',
            'Saguin',
            'Valladolid',
            'Mello',
            'Sibayan',
            'Sierra',
            'Tumbaga',
            'Sandoval',
            'Ocampo',
            'Almazan',
            'Reynoso',
            'Suarez',
            'Mira',
            'Duran',
            'Taboada',
            'Carreon',
            'Bulaong',
            'De Guzman',
            'Vicente',
            'Palomar',
            'Ventura',
            'Meneses',
            'Tanjay',
            'Gonzaga',
            'De La Vega',
            'Legarda',
            'Dianalan',
            'Almeda',
            'Vega',
            'Almario',
            'Malvar',
            'Rosario',
            'Tagapulot',
            'Martelino',
            'Sungan',
            'Gabas',
            'Liaño',
            'Hapitan',
            'Ramirez',
            'Gonzales',
            'Guerrero',
            'Belmonte',
            'Gonzalo',
            'Dychangco',
            'Macalino',
            'Rosal',
            'Dorado',
            'Yap',
            'Castro',
            'Lopez',
            'Guerrero',
            'Evangelista',
            'Montano',
            'Hernandez',
            'Moreno',
            'Sanchez',
            'Reyes',
            'Enriquez',
            'Zuniga',
            'Garcia',
            'Dumanjug',
            'Santos',
            'Rosales',
            'Ocampo',
            'Balingit',
            'Candelaria',
            'Castillejo',
            'Bautista',
            'Serapio',
            'Marañon',
            'Olores',
            'Rosalinda',
            'Santos',
            'Molina',
            'Isla'
        ];

        $otherArrangements = [
            'Living with Extended Family',
            'Living with Non-relatives',
            'Living in a Shared Rental Property',
            'Living Temporarily in a Shelter',
            'Living in a Boarding House/Dormitory',
            'Living in a Residential Care Facility',
            'Co-living Spaces',
            'Living in a Hostel or Temporary Accommodation',
            'Living in a Commune or Cooperative Housing',
            'Living Independently in Mobile Housing',
            'Living as a Nomad',
            'Living with a Foster Family',
            'Living with a Legal Guardian',
            'Incarcerated or Detained',
            'Institutional Living',
            'Sa Kalsada lang po',
            'Sa tabing Ilog',
            'Naninirahan lang',
            'Walang permanenteng tirahan',
        ];

        $existing_illness = [
            'Hypertension',
            'Diabetes',
            'Arthritis',
            'Heart disease',
            'Chronic obstructive pulmonary disease (COPD)',
            'Dementia',
            'Alzheimer disease',
            'Osteoporosis',
            'Cancer',
            'Kidney disease',
            'Stroke',
            'Parkinson disease',
            'Depression',
            'Anxiety disorders',
            'Vision impairment',
            'Hearing loss',
            'Chronic pain conditions',
            'Gastroesophageal reflux disease (GERD)',
            'Hypothyroidism'
        ];

        $existing_disability = [
            'Visual impairment',
            'Hearing impairment',
            'Mobility impairment',
            'Cognitive disability', 
            'Mental health condition'
        ];

        $maleProfilePictures = [
            "sample2.png",
            "sample3.jpg",
            "sample6.jpg",
            "sample7.jpg",
            "sample10.jpg",
            "sample11.jpg",
            "sample12.jpg",
            "sample13.jpg",
            "sample15.jpg",
            "sample17.jpg",
            "sample20.jpg",
            "sample21.jpg",
            "sample22.jpg"
        ];

        $femaleProfilePictures = [
            "sample1.png",
            "sample4.jpg",
            "sample5.jpg",
            "sample8.jpg",
            "sample9.jpg",
            "sample14.jpg",
            "sample16.jpg",
            "sample18.jpg",
            "sample19.jpg"
        ];

        $baseTimestamp = strtotime('-5 years');
        $nowTimestamp = time();
        $totalUsers = 500;
        $usersLeft = $totalUsers;

        $usersPerDay = [];

        while ($usersLeft > 0) {

            $dateTimestamp = rand($baseTimestamp, $nowTimestamp);
            $date = date('Y-m-d', $dateTimestamp);

            $NumberOfUsers = rand(1, min(5, $usersLeft));
            $usersPerDay[$date] = ($usersPerDay[$date] ?? 0) + $NumberOfUsers;

            $usersLeft -= $NumberOfUsers;
        }

        foreach ($usersPerDay as $date => $NumberOfUsers) {
            for ($i = 0; $i < $NumberOfUsers; $i++) {
                $timestamp_applied = strtotime($date . ' ' . rand(0, 23) . ':' . rand(0, 59) . ':' . rand(0, 59));
                if ($timestamp_applied > $nowTimestamp) {
                    $timestamp_applied = $nowTimestamp;
                }
                $date_applied = date('Y-m-d H:i:s', $timestamp_applied);

                $timestamp_approved = strtotime('+1 week', $timestamp_applied);
                if ($timestamp_approved > $nowTimestamp) {
                    $timestamp_approved = $nowTimestamp;
                }
                $date_approved = date('Y-m-d H:i:s', $timestamp_approved);

            }
        }

        $has_illness = $this->faker->numberBetween(0, 1);
        $has_disability = $this->faker->randomElement([0, 0, 0, 1]);
        $permanent_source = $this->faker->randomElement([0, 1]);
        $pensioner = $this->faker->randomElement([0, 1]);
        $application_assistant_id = $this->faker->numberBetween(2, 3);
        $registration_assistant_id = $this->faker->numberBetween(2, 3);
        $type_of_living_arrangement = $this->faker->numberBetween(1, 5);
        $isMale = $this->faker->boolean();
        $firstName = $isMale ? $this->faker->randomElement($maleNames) : $this->faker->randomElement($femaleNames);
        $sex = $isMale ? 1 : 2;
        $randomChance = rand(1, 10);

        if ($randomChance > 2) {
            if ($sex == 1) { 
                $profile_picture = $maleProfilePictures[array_rand($maleProfilePictures)];
            } else { 
                $profile_picture = $femaleProfilePictures[array_rand($femaleProfilePictures)];
            }
        } else {
            $profile_picture = null;
        }

        $uniqueEmails = [];

        return [
            'osca_id' => function () {
                do {
                    $oscaId = fake()->numberBetween(10000, 99999);
                } while (\App\Models\Seniors::where('osca_id', $oscaId)->exists());

                return $oscaId;
            },

            'date_applied' => $date_applied,
            'date_approved' => $date_approved,
            'ncsc_rrn' => function (array $attributes) {
                return date('Y-m-d', strtotime($attributes['date_applied'])) . '-' . $attributes['osca_id'];
            },

            'application_status_id' => function () {
                $weights = [
                    1 => 1,
                    2 => 1,
                    3 => 5,
                    4 => 1,
                ];

                $weightedValues = [];
                foreach ($weights as $value => $weight) {
                    for ($i = 0; $i < $weight; $i++) {
                        $weightedValues[] = $value;
                    }
                }

                return $this->faker->randomElement($weightedValues);
            },

            'account_status_id' => function (array $attributes) {
                return $attributes['application_status_id'] === 3
                ? (rand(1, 100) <= 75
                    ? 1
                    : $this->faker->numberBetween(2, 4))
                    : null;
            },

            'application_assistant_id' => function (array $attributes) use ($application_assistant_id) {
                return $attributes['application_status_id'] === 3
                ? $application_assistant_id
                : null;
            },

            'application_encoder_id' => function (array $attributes) {
                if ($attributes['application_assistant_id'] === 2) {
                    return $this->faker->numberBetween(1, 30);
                }
                return null;
            },

            'application_admin_id' => function (array $attributes) {
                if ($attributes['application_assistant_id'] === 3) {
                    return 1;
                }
                return null;
            },

            'application_assistant_name' => function (array $attributes) use ($application_assistant_id) {
                if ($attributes['application_status_id'] === 3 && $application_assistant_id) {
                    if ($application_assistant_id === 2) {
                        $encoderId = $attributes['application_encoder_id'] ?? null;
                        if ($encoderId) {
                            $encoder = \App\Models\Encoder::find($encoderId);
                            return $encoder ? $encoder->encoder_first_name . ' ' . $encoder->encoder_last_name : null;
                        }
                    } elseif ($application_assistant_id === 3) {
                        $adminId = $attributes['application_admin_id'] ?? null;
                        if ($adminId) {
                            $admin = \App\Models\Admin::find($adminId);
                            return $admin ? $admin->admin_first_name . ' ' . $admin->admin_last_name : null;
                        }
                    }
                }
                return null;
            },

            'registration_assistant_id' => function (array $attributes) use ($registration_assistant_id) {
                return $attributes['application_status_id'] === 3
                ? ($registration_assistant_id ?? null)
                : null;
            },

            'registration_encoder_id' => function (array $attributes) {
                if ($attributes['registration_assistant_id'] === 2) {
                    return $this->faker->numberBetween(1, 30);
                }
                return null;
            },

            'registration_admin_id' => function (array $attributes) {
                if ($attributes['registration_assistant_id'] === 3) {
                    return 1;
                }
                return null;
            },

            'registration_assistant_name' => function (array $attributes) use ($registration_assistant_id) {
                if ($attributes['application_status_id'] === 3 && $registration_assistant_id) {
                    if ($registration_assistant_id === 2) {
                        $encoderId = $attributes['registration_encoder_id'] ?? null;
                        if ($encoderId) {
                            $encoder = \App\Models\Encoder::find($encoderId);
                            return $encoder ? $encoder->encoder_first_name . ' ' . $encoder->encoder_last_name : null;
                        }
                    } elseif ($registration_assistant_id === 3) {
                        $adminId = $attributes['registration_admin_id'] ?? null;
                        if ($adminId) {
                            $admin = \App\Models\Admin::find($adminId);
                            return $admin ? $admin->admin_first_name . ' ' . $admin->admin_last_name : null;
                        }
                    }
                }
                return null;
            },

            'user_type_id' => 1,

            'first_name' => $firstName,
            'middle_name' => function () use ($filipinoLastNames) {
                return $this->faker->randomElement(array_merge($filipinoLastNames, [null, null, null]));
            },
            'last_name' => $this->faker->randomElement($filipinoLastNames),
            'suffix' => $isMale ? $this->faker->randomElement([null, null, null, 'Jr.', 'Sr.', 'I', 'II', 'III']) : null,
            'birthdate' => $birthdate,
            'age' => $age,
            'birthplace' => $this->faker->randomElement($philippineCities),
            'sex_id' => $sex,
            'civil_status_id' => $this->faker->numberBetween(1, 4),
            'contact_no' => $this->faker->regexify('\+639[0-9]{9}'),
            'address' => $address,
            'barangay_id' => $barangayIndex,
            'valid_id' => 'sample4.png',
            'profile_picture' => $profile_picture,
            'indigency' => 'sample5.jpg',
            'birth_certificate' => 'sample3.jpg',
            'signature_data' => 'sample6.png',
            'type_of_living_arrangement' => $type_of_living_arrangement,
            'other_arrangement_remark' => $type_of_living_arrangement == 5 ? $this->faker->randomElement($otherArrangements) : null,
            'pensioner' => $pensioner,
            'if_pensioner_yes' => $pensioner == 1 ? $this->faker->numberBetween(1, 11) : null,
            'permanent_source' => $permanent_source,
            'if_permanent_yes_income' => $permanent_source == 1 ? $this->faker->numberBetween(1, 11) : null,
            'has_illness' => $has_illness,
            'has_disability' => $has_disability,
            'if_illness_yes' => $has_illness == 1 ? $this->faker->randomElement($existing_illness) : null,
            'if_disability_yes' => $has_disability == 1 ? $this->faker->randomElement($existing_disability) : null,
            'email' => function () use (&$uniqueEmails, $firstName, $filipinoLastNames) {
                do {
                    $email = strtolower(str_replace(' ', '', $firstName) . '.' . rand(100, 999) . '.' . str_replace(' ', '', $this->faker->randomElement($filipinoLastNames)) . '@example.com');
                    $emailExists = DB::table('seniors')->where('email', $email)->exists();
                } while (in_array($email, $uniqueEmails) || $emailExists);
                $uniqueEmails[] = $email;

                return $email;
            },
            'password' => Hash::make('password'),
            'verified_at' => $this->faker->dateTimeBetween('-1 year', 'now'),
        ];
    }

    /**
     * Indicate that the model's email address should be unverified.
     */
    public function unverified(): static
    {
        return $this->state(fn(array $attributes) => [
            'email_verified_at' => null,
        ]);
    }
}
