<?php

namespace Database\Factories;

use Illuminate\Database\Eloquent\Factories\Factory;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\User>
 */
class SeniorsFactory extends Factory
{
    /**
     * The current password being used by the factory.
     */
    protected static ?string $password;

    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        $age = $this->faker->numberBetween(60, 100);

        $birthdate = now()->subYears($age)->toDateString();

        $filipinoStreet = [
            'Maligaya Street',
            'Mabait Drive',
            'Malolos Avenue',
            'Daisy Road',
            'Camia Boulevard',
            'Sampaguita Street',
            'Rosal Drive',
            'Ruby Avenue',
            'Emerald Boulevard',
            'Gemini Street',
            'Sunflower Drive',
            'Tulip Road',
            'Jade Avenue',
            'Pearl Boulevard',
            'Santos Street',
            'Magnolia Avenue',
            'Ilang-Ilang Drive',
            'Waling-Waling Boulevard',
            'Champaca Street',
            'Dama de Noche Avenue',
            'Venus Road',
            'Saturn Street',
            'Mars Drive',
            'Orion Boulevard',
            'Aurora Avenue',
            'Luna Street',
            'Kalayaan Drive',
            'Masaya Road',
            'Pag-asa Street',
            'Matahimik Avenue',
            'Makisig Boulevard',
            'Marangal Drive',
            'Magiting Street',
            'Mabuhay Road',
            'Mapayapa Avenue',
            'Matatag Drive',
            'Matapat Boulevard',
            'Matamis Street',
            'Mahinhin Drive',
            'Maharlika Avenue',
            'Anahaw Road',
            'Acacia Street',
            'Yakal Boulevard',
            'Narra Drive',
            'Kamagong Street',
            'Molave Avenue',
            'Banaba Road',
            'Talisay Drive',
            'Santol Street',
            'Mangga Avenue',
            'Bayabas Drive',
            'Makopa Street',
            'Kalamansi Road',
            'Atis Drive',
            'Langka Street',
            'Papaya Boulevard',
            'Guyabano Avenue',
            'Siniguelas Drive',
            'Avocado Street',
            'Chico Road',
            'Guava Drive',
            'Balete Boulevard',
            'Pineapple Avenue',
            'Cherry Drive',
            'Rambutan Street',
            'Dalandan Road',
            'Jasmine Street',
            'Azucena Drive',
            'Gardenia Boulevard',
            'Lily Avenue',
            'Poinsettia Street',
            'Gumamela Drive',
            'Hydrangea Road',
            'Bluebell Boulevard',
            'Iris Avenue',
            'Violeta Street',
            'Zinnia Drive',
            'Carnation Road',
            'Hibiscus Boulevard',
            'Marigold Street',
            'Cosmos Drive',
            'Petunia Road',
            'Lavender Avenue',
            'Rose Street',
            'Gladiola Boulevard',
            'Peridot Avenue',
            'Topaz Street',
            'Amethyst Drive',
            'Opal Road',
            'Diamond Boulevard',
            'Sapphire Street',
            'Garnet Drive',
            'Turquoise Road',
            'Citrine Avenue',
            'Amber Street',
            'Coral Boulevard',
            'Onyx Drive',
            'Aquamarine Avenue',
            'Silver Street',
            'Gold Boulevard'
        ];

        $philippineCities = [
            'Caloocan City',
            'Quezon City',
            'Manila',
            'Cebu City',
            'Davao City',
            'Zamboanga City',
            'Baguio City',
            'Iloilo City',
            'Taguig City',
            'Cavite City',

            'General Santos City',
            'Makati City',
            'Pasig City',
            'Marikina City',
            'San Juan City',
            'Las Piñas City',
            'Parañaque City',
            'Malabon City',
            'Navotas City',
            'Mandaluyong City',

            'Calamba City',
            'Bacoor City',
            'Cagayan de Oro City',
            'Lapu-Lapu City',
            'Angeles City',
            'San Fernando City (Pampanga)',
            'Tarlac City',
            'San Carlos City (Pangasinan)',

            'Iligan City',
            'Digos City',
            'Tacloban City',
            'Tagum City',
            'Puerto Princesa City',
            'Ormoc City',
            'Bayugan City',
            'Dipolog City',
            'Marawi City',
            'Cotabato City',

            'Legazpi City',
            'Naga City',
            'Cabanatuan City',
            'Santiago City',
            'Tuguegarao City',
            'San Jose City (Occidental Mindoro)',
            'San Jose del Monte City',
            'Mandaue City',
            'Dumaguete City',
            'Calapan City',
        ];

        $houseNumber = $this->faker->numberBetween(1000, 9999);
        $phase = 'Phase ' . $this->faker->numberBetween(1, 10);
        $block = 'Block ' . $this->faker->numberBetween(1, 90);
        $lot = 'Lot ' . $this->faker->numberBetween(1, 90);
        $barangayNo = $this->faker->numberBetween(165, 188);
        $filipinoStreet = $this->faker->randomElement($filipinoStreet);
        $address = "{$houseNumber} {$phase} {$block} {$lot} {$filipinoStreet}, Brgy. {$barangayNo}, Caloocan City";

        $maleNames = [
            'John',
            'Mark',
            'Michael',
            'James',
            'Robert',
            'William',
            'David',
            'Richard',
            'Joseph',
            'Charles',
            'Thomas',
            'Daniel',
            'Matthew',
            'Anthony',
            'Donald',
            'Paul',
            'Andrew',
            'Joshua',
            'Samuel',
            'Kevin',
            'Brian',
            'George',
            'Edward',
            'Ronald',
            'Jack',
            'Jason',
            'Justin',
            'Larry',
            'Scott',
            'Eric',
            'Stephen',
            'Timothy',
            'Daniel',
            'Adam',
            'Nathan'
        ];

        $femaleNames = [
            'Mary',
            'Jennifer',
            'Linda',
            'Patricia',
            'Elizabeth',
            'Barbara',
            'Susan',
            'Jessica',
            'Sarah',
            'Margaret',
            'Dorothy',
            'Laura',
            'Helen',
            'Nancy',
            'Karen',
            'Betty',
            'Ruth',
            'Sharon',
            'Kimberly',
            'Deborah',
            'Cynthia',
            'Amy',
            'Angela',
            'Virginia',
            'Diane',
            'Julie',
            'Madison',
            'Sophia',
            'Isabella',
            'Charlotte',
            'Ava',
            'Mia',
            'Emma',
            'Harper',
            'Ella'
        ];

        $filipinoLastNames = [
            'Cabigon',
            'Santiago',
            'Palomares',
            'Tonio',
            'Aquino',
            'Bautista',
            'Cruz',
            'Dela Cruz',
            'Gonzales',
            'Garcia',
            'López',
            'Martinez',
            'Reyes',
            'Santos',
            'Torres',
            'Delos Reyes',
            'Bañez',
            'Flores',
            'Nieves',
            'Salvador',
            'Dizon',
            'Bacani',
            'Velasquez',
            'Cabrera',
            'Pascual',
            'Villanueva',
            'Alvarez',
            'Chua',
            'Sarmiento',
            'Morales',
            'Pineda',
            'Ocampo',
            'Alcantara',
            'Cortez',
            'Alvarado',
            'Mendoza',
            'Labrador',
            'Salinas',
            'Castañeda',
            'De Leon',
            'Vera',
            'Magsaysay',
            'Dela Torre',
            'Ponce',
            'Suarez',
            'Valenzuela',
            'Aguilar',
            'Ramos',
            'Cruzado',
            'Esteban',
            'Sison',
            'Tiongson',
            'San Antonio',
            'Dela Cruz',
            'Del Mundo',
            'De Guzman',
            'De Jesus',
            'De Leon',
            'Delos Santos',
            'De Vera',
            'San Miguel',
            'San Juan',
            'San Pedro',
            'De Ocampo',
            'Del Rosario',
            'De la Torre',
            'De la Cruz',
            'San Vicente',
            'Del Castillo',
            'De la Vega',
            'Bautista',
            'Cruz',
            'Mendoza',
            'Martinez',
            'Riviera',
            'Salas',
            'Rocamora',
            'Santos',
            'Tabujara',
            'Verano',
            'Villanueva',
            'Castillo',
            'Martelino',
            'Misa',
            'Naguit',
            'Alcaraz',
            'Alfonso',
            'Arroyo',
            'Atienza',
            'Bañez',
            'Cabarroguis',
            'Esguerra',
            'Manalo',
            'Matias',
            'Ramos',
            'Villafuerte',
            'Yap',
            'Zaragoza',
            'De Guzman',
            'De la Rosa',
            'Delos Reyes',
            'De Guzman',
            'De Villa',
            'Gumabay',
            'Lacuna',
            'Macapagal',
            'Manalaysay',
            'Natividad',
            'Rosales',
            'Soriano',
        ];

        $isMale = $this->faker->boolean();
        $firstName = $isMale ? $this->faker->randomElement($maleNames) : $this->faker->randomElement($femaleNames);
        $sex = $isMale ? 'Male' : 'Female';

        return [
            'first_name' => $firstName,
            'middle_name' => $this->faker->randomElement($filipinoLastNames),
            'last_name' => $this->faker->randomElement($filipinoLastNames),
            'suffix' => $this->faker->suffix(),
            'birthdate' => $birthdate,
            'age' => $age,
            'birthplace' => $this->faker->randomElement($philippineCities),
            'sex' => $sex,
            'civil_status' => $this->faker->randomElement(['Single', 'Married', 'Widowed', 'Divorced']),
            'employment_status' => $this->faker->randomElement(['Employed', 'Unemployed', 'Retired']),
            'religion' => $this->faker->randomElement(['Catholic', 'Christian', 'Muslim', 'Other']),
            'blood_type' => $this->faker->randomElement(['A', 'B', 'AB', 'O']),
            'address' => $address,
            'barangay' => $barangayNo,
            'telephone_number' => $this->faker->numerify('82##-####'),
            'existing_email' => strtolower($firstName . '.' . $this->faker->randomNumber(3) . '.' . $this->faker->randomElement($filipinoLastNames) . '@example.com'),
            'mobile_number' => '+63' . $this->faker->randomNumber(9, true),
            'gsis_number' => $this->faker->numerify('GSIS#######'),
            'sss_number' => $this->faker->numerify('SSS#######'),
            'tin_number' => $this->faker->numerify('TIN#######'),
            'philhealth_number' => $this->faker->numerify('PH#######'),
            'valid_id' => null,
            'profile_picture' => null,

            'email' => strtolower($firstName . '.' . $this->faker->randomNumber(3) . '.' . $this->faker->randomElement($filipinoLastNames) . '@example.com'),
            'password' => Hash::make('password'),
        ];
    }

    /**
     * Indicate that the model's email address should be unverified.
     */
    public function unverified(): static
    {
        return $this->state(fn(array $attributes) => [
            'email_verified_at' => null,
        ]);
    }
}
